// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum HostPlaybackState {
  idle,
  loading,
  ready,
  playing,
  paused,
  buffering,
  completed,
  error,
  disposed,
}

enum HostErrorCode {
  sourceUnreachable,
  sourceUnsupported,
  decodeFailed,
  timedOut,
  licenseDenied,
  unknown,
}

enum HostEventKind {
  playbackState,
  position,
  buffered,
  error,
  videoTracks,
  audioTracks,
  textTracks,
  subtitleCues,
  droppedFrames,
  live,
  pictureInPicture,
  backgroundAudio,
  mediaCommand,
}

enum HostPictureInPictureState { unavailable, inactive, active }

enum HostPictureInPictureExitKind { restored, dismissed }

enum HostBackgroundAudioState { unavailable, inactive, active }

enum HostMediaCommand { next, previous }

enum HostSourceKind { network, file, asset, content, offline }

enum HostDrmScheme { widevine, fairPlay, clearKey }

class HostBufferedRange {
  HostBufferedRange({required this.startMs, required this.endMs});

  int startMs;

  int endMs;

  List<Object?> _toList() {
    return <Object?>[startMs, endMs];
  }

  Object encode() {
    return _toList();
  }

  static HostBufferedRange decode(Object result) {
    result as List<Object?>;
    return HostBufferedRange(
      startMs: result[0]! as int,
      endMs: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostBufferedRange || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(startMs, other.startMs) &&
        _deepEquals(endMs, other.endMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostVideoTrack {
  HostVideoTrack({
    required this.id,
    this.width,
    this.height,
    this.bitrate,
    this.codec,
  });

  String id;

  int? width;

  int? height;

  int? bitrate;

  String? codec;

  List<Object?> _toList() {
    return <Object?>[id, width, height, bitrate, codec];
  }

  Object encode() {
    return _toList();
  }

  static HostVideoTrack decode(Object result) {
    result as List<Object?>;
    return HostVideoTrack(
      id: result[0]! as String,
      width: result[1] as int?,
      height: result[2] as int?,
      bitrate: result[3] as int?,
      codec: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostVideoTrack || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(bitrate, other.bitrate) &&
        _deepEquals(codec, other.codec);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostAudioTrack {
  HostAudioTrack({
    required this.id,
    this.language,
    this.label,
    this.channels,
    this.codec,
  });

  String id;

  String? language;

  String? label;

  int? channels;

  String? codec;

  List<Object?> _toList() {
    return <Object?>[id, language, label, channels, codec];
  }

  Object encode() {
    return _toList();
  }

  static HostAudioTrack decode(Object result) {
    result as List<Object?>;
    return HostAudioTrack(
      id: result[0]! as String,
      language: result[1] as String?,
      label: result[2] as String?,
      channels: result[3] as int?,
      codec: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostAudioTrack || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(language, other.language) &&
        _deepEquals(label, other.label) &&
        _deepEquals(channels, other.channels) &&
        _deepEquals(codec, other.codec);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostTextTrack {
  HostTextTrack({required this.id, this.language, this.label, this.codec});

  String id;

  String? language;

  String? label;

  String? codec;

  List<Object?> _toList() {
    return <Object?>[id, language, label, codec];
  }

  Object encode() {
    return _toList();
  }

  static HostTextTrack decode(Object result) {
    result as List<Object?>;
    return HostTextTrack(
      id: result[0]! as String,
      language: result[1] as String?,
      label: result[2] as String?,
      codec: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostTextTrack || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(language, other.language) &&
        _deepEquals(label, other.label) &&
        _deepEquals(codec, other.codec);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostSubtitleCue {
  HostSubtitleCue({required this.text});

  String text;

  List<Object?> _toList() {
    return <Object?>[text];
  }

  Object encode() {
    return _toList();
  }

  static HostSubtitleCue decode(Object result) {
    result as List<Object?>;
    return HostSubtitleCue(text: result[0]! as String);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostSubtitleCue || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(text, other.text);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostPlayerEvent {
  HostPlayerEvent({
    required this.kind,
    required this.playerId,
    this.playbackState,
    this.positionMs,
    this.durationMs,
    this.buffered,
    this.errorCode,
    this.errorMessage,
    this.nativeDetails,
    this.isRecoverable,
    this.videoTracks,
    this.selectedVideoTrackId,
    this.videoTrackAuto,
    this.audioTracks,
    this.selectedAudioTrackId,
    this.audioTrackAuto,
    this.textTracks,
    this.selectedTextTrackId,
    this.textTrackAuto,
    this.subtitleCues,
    this.droppedFrameCount,
    this.isLive,
    this.liveOffsetMs,
    this.pictureInPictureState,
    this.pictureInPictureExit,
    this.backgroundAudioState,
    this.mediaCommand,
  });

  HostEventKind kind;

  int playerId;

  HostPlaybackState? playbackState;

  int? positionMs;

  int? durationMs;

  List<HostBufferedRange>? buffered;

  HostErrorCode? errorCode;

  String? errorMessage;

  String? nativeDetails;

  bool? isRecoverable;

  List<HostVideoTrack>? videoTracks;

  String? selectedVideoTrackId;

  bool? videoTrackAuto;

  List<HostAudioTrack>? audioTracks;

  String? selectedAudioTrackId;

  bool? audioTrackAuto;

  List<HostTextTrack>? textTracks;

  String? selectedTextTrackId;

  bool? textTrackAuto;

  List<HostSubtitleCue>? subtitleCues;

  int? droppedFrameCount;

  bool? isLive;

  int? liveOffsetMs;

  HostPictureInPictureState? pictureInPictureState;

  HostPictureInPictureExitKind? pictureInPictureExit;

  HostBackgroundAudioState? backgroundAudioState;

  HostMediaCommand? mediaCommand;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      playerId,
      playbackState,
      positionMs,
      durationMs,
      buffered,
      errorCode,
      errorMessage,
      nativeDetails,
      isRecoverable,
      videoTracks,
      selectedVideoTrackId,
      videoTrackAuto,
      audioTracks,
      selectedAudioTrackId,
      audioTrackAuto,
      textTracks,
      selectedTextTrackId,
      textTrackAuto,
      subtitleCues,
      droppedFrameCount,
      isLive,
      liveOffsetMs,
      pictureInPictureState,
      pictureInPictureExit,
      backgroundAudioState,
      mediaCommand,
    ];
  }

  Object encode() {
    return _toList();
  }

  static HostPlayerEvent decode(Object result) {
    result as List<Object?>;
    return HostPlayerEvent(
      kind: result[0]! as HostEventKind,
      playerId: result[1]! as int,
      playbackState: result[2] as HostPlaybackState?,
      positionMs: result[3] as int?,
      durationMs: result[4] as int?,
      buffered: (result[5] as List<Object?>?)?.cast<HostBufferedRange>(),
      errorCode: result[6] as HostErrorCode?,
      errorMessage: result[7] as String?,
      nativeDetails: result[8] as String?,
      isRecoverable: result[9] as bool?,
      videoTracks: (result[10] as List<Object?>?)?.cast<HostVideoTrack>(),
      selectedVideoTrackId: result[11] as String?,
      videoTrackAuto: result[12] as bool?,
      audioTracks: (result[13] as List<Object?>?)?.cast<HostAudioTrack>(),
      selectedAudioTrackId: result[14] as String?,
      audioTrackAuto: result[15] as bool?,
      textTracks: (result[16] as List<Object?>?)?.cast<HostTextTrack>(),
      selectedTextTrackId: result[17] as String?,
      textTrackAuto: result[18] as bool?,
      subtitleCues: (result[19] as List<Object?>?)?.cast<HostSubtitleCue>(),
      droppedFrameCount: result[20] as int?,
      isLive: result[21] as bool?,
      liveOffsetMs: result[22] as int?,
      pictureInPictureState: result[23] as HostPictureInPictureState?,
      pictureInPictureExit: result[24] as HostPictureInPictureExitKind?,
      backgroundAudioState: result[25] as HostBackgroundAudioState?,
      mediaCommand: result[26] as HostMediaCommand?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostPlayerEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(playerId, other.playerId) &&
        _deepEquals(playbackState, other.playbackState) &&
        _deepEquals(positionMs, other.positionMs) &&
        _deepEquals(durationMs, other.durationMs) &&
        _deepEquals(buffered, other.buffered) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(errorMessage, other.errorMessage) &&
        _deepEquals(nativeDetails, other.nativeDetails) &&
        _deepEquals(isRecoverable, other.isRecoverable) &&
        _deepEquals(videoTracks, other.videoTracks) &&
        _deepEquals(selectedVideoTrackId, other.selectedVideoTrackId) &&
        _deepEquals(videoTrackAuto, other.videoTrackAuto) &&
        _deepEquals(audioTracks, other.audioTracks) &&
        _deepEquals(selectedAudioTrackId, other.selectedAudioTrackId) &&
        _deepEquals(audioTrackAuto, other.audioTrackAuto) &&
        _deepEquals(textTracks, other.textTracks) &&
        _deepEquals(selectedTextTrackId, other.selectedTextTrackId) &&
        _deepEquals(textTrackAuto, other.textTrackAuto) &&
        _deepEquals(subtitleCues, other.subtitleCues) &&
        _deepEquals(droppedFrameCount, other.droppedFrameCount) &&
        _deepEquals(isLive, other.isLive) &&
        _deepEquals(liveOffsetMs, other.liveOffsetMs) &&
        _deepEquals(pictureInPictureState, other.pictureInPictureState) &&
        _deepEquals(pictureInPictureExit, other.pictureInPictureExit) &&
        _deepEquals(backgroundAudioState, other.backgroundAudioState) &&
        _deepEquals(mediaCommand, other.mediaCommand);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class CreatePlayerResult {
  CreatePlayerResult({
    required this.playerId,
    required this.textureId,
    required this.pictureInPictureState,
    required this.backgroundAudioState,
  });

  int playerId;

  int textureId;

  HostPictureInPictureState pictureInPictureState;

  HostBackgroundAudioState backgroundAudioState;

  List<Object?> _toList() {
    return <Object?>[
      playerId,
      textureId,
      pictureInPictureState,
      backgroundAudioState,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CreatePlayerResult decode(Object result) {
    result as List<Object?>;
    return CreatePlayerResult(
      playerId: result[0]! as int,
      textureId: result[1]! as int,
      pictureInPictureState: result[2]! as HostPictureInPictureState,
      backgroundAudioState: result[3]! as HostBackgroundAudioState,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CreatePlayerResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(playerId, other.playerId) &&
        _deepEquals(textureId, other.textureId) &&
        _deepEquals(pictureInPictureState, other.pictureInPictureState) &&
        _deepEquals(backgroundAudioState, other.backgroundAudioState);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostDrmConfiguration {
  HostDrmConfiguration({
    required this.scheme,
    this.licenseUrl,
    this.licenseHeaders,
    this.clearKeys,
    this.certificate,
    this.contentId,
  });

  HostDrmScheme scheme;

  String? licenseUrl;

  Map<String, String>? licenseHeaders;

  Map<String, String>? clearKeys;

  Uint8List? certificate;

  String? contentId;

  List<Object?> _toList() {
    return <Object?>[
      scheme,
      licenseUrl,
      licenseHeaders,
      clearKeys,
      certificate,
      contentId,
    ];
  }

  Object encode() {
    return _toList();
  }

  static HostDrmConfiguration decode(Object result) {
    result as List<Object?>;
    return HostDrmConfiguration(
      scheme: result[0]! as HostDrmScheme,
      licenseUrl: result[1] as String?,
      licenseHeaders: (result[2] as Map<Object?, Object?>?)
          ?.cast<String, String>(),
      clearKeys: (result[3] as Map<Object?, Object?>?)?.cast<String, String>(),
      certificate: result[4] as Uint8List?,
      contentId: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostDrmConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(scheme, other.scheme) &&
        _deepEquals(licenseUrl, other.licenseUrl) &&
        _deepEquals(licenseHeaders, other.licenseHeaders) &&
        _deepEquals(clearKeys, other.clearKeys) &&
        _deepEquals(certificate, other.certificate) &&
        _deepEquals(contentId, other.contentId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostMediaSource {
  HostMediaSource({
    required this.kind,
    required this.location,
    this.packageName,
    this.headers,
    this.drm,
  });

  HostSourceKind kind;

  /// Network URI, absolute file path / `file://` URI, Flutter asset key,
  /// `content://` URI, or download id for [HostSourceKind.offline].
  String location;

  /// Flutter package name for [HostSourceKind.asset]. Null for the app bundle.
  String? packageName;

  /// HTTP headers for [HostSourceKind.network] only. Null or empty = none.
  Map<String, String>? headers;

  /// License config for protected playback. Null = clear content.
  HostDrmConfiguration? drm;

  List<Object?> _toList() {
    return <Object?>[kind, location, packageName, headers, drm];
  }

  Object encode() {
    return _toList();
  }

  static HostMediaSource decode(Object result) {
    result as List<Object?>;
    return HostMediaSource(
      kind: result[0]! as HostSourceKind,
      location: result[1]! as String,
      packageName: result[2] as String?,
      headers: (result[3] as Map<Object?, Object?>?)?.cast<String, String>(),
      drm: result[4] as HostDrmConfiguration?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostMediaSource || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(location, other.location) &&
        _deepEquals(packageName, other.packageName) &&
        _deepEquals(headers, other.headers) &&
        _deepEquals(drm, other.drm);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostPipSourceRect {
  HostPipSourceRect({
    required this.left,
    required this.top,
    required this.width,
    required this.height,
  });

  int left;

  int top;

  int width;

  int height;

  List<Object?> _toList() {
    return <Object?>[left, top, width, height];
  }

  Object encode() {
    return _toList();
  }

  static HostPipSourceRect decode(Object result) {
    result as List<Object?>;
    return HostPipSourceRect(
      left: result[0]! as int,
      top: result[1]! as int,
      width: result[2]! as int,
      height: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostPipSourceRect || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(left, other.left) &&
        _deepEquals(top, other.top) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostLicenseInfo {
  HostLicenseInfo({required this.features, this.expiresAtUnix});

  /// [PaidFeature] ids unlocked by this token.
  List<String> features;

  int? expiresAtUnix;

  List<Object?> _toList() {
    return <Object?>[features, expiresAtUnix];
  }

  Object encode() {
    return _toList();
  }

  static HostLicenseInfo decode(Object result) {
    result as List<Object?>;
    return HostLicenseInfo(
      features: (result[0]! as List<Object?>).cast<String>(),
      expiresAtUnix: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostLicenseInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(features, other.features) &&
        _deepEquals(expiresAtUnix, other.expiresAtUnix);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is HostPlaybackState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is HostErrorCode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is HostEventKind) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is HostPictureInPictureState) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is HostPictureInPictureExitKind) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is HostBackgroundAudioState) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is HostMediaCommand) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is HostSourceKind) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is HostDrmScheme) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is HostBufferedRange) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is HostVideoTrack) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is HostAudioTrack) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is HostTextTrack) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is HostSubtitleCue) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is HostPlayerEvent) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is CreatePlayerResult) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is HostDrmConfiguration) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is HostMediaSource) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is HostPipSourceRect) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is HostLicenseInfo) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostPlaybackState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostErrorCode.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostEventKind.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostPictureInPictureState.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : HostPictureInPictureExitKind.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostBackgroundAudioState.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostMediaCommand.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostSourceKind.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostDrmScheme.values[value];
      case 138:
        return HostBufferedRange.decode(readValue(buffer)!);
      case 139:
        return HostVideoTrack.decode(readValue(buffer)!);
      case 140:
        return HostAudioTrack.decode(readValue(buffer)!);
      case 141:
        return HostTextTrack.decode(readValue(buffer)!);
      case 142:
        return HostSubtitleCue.decode(readValue(buffer)!);
      case 143:
        return HostPlayerEvent.decode(readValue(buffer)!);
      case 144:
        return CreatePlayerResult.decode(readValue(buffer)!);
      case 145:
        return HostDrmConfiguration.decode(readValue(buffer)!);
      case 146:
        return HostMediaSource.decode(readValue(buffer)!);
      case 147:
        return HostPipSourceRect.decode(readValue(buffer)!);
      case 148:
        return HostLicenseInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

class PlayerHostApi {
  /// Constructor for [PlayerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PlayerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Verifies [token] against this app's package / bundle id. Process-wide.
  Future<HostLicenseInfo> activateLicense(String token) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.activateLicense$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[token],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HostLicenseInfo;
  }

  Future<CreatePlayerResult> create() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.create$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CreatePlayerResult;
  }

  Future<void> load(int playerId, HostMediaSource source) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.load$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, source],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> play(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> pause(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> seek(int playerId, int positionMs) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.seek$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, positionMs],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setVolume(int playerId, double volume) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.setVolume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, volume],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setPlaybackSpeed(int playerId, double speed) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.setPlaybackSpeed$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, speed],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setLooping(int playerId, bool looping) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.setLooping$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, looping],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setVideoTrack(int playerId, String? trackId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.setVideoTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, trackId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setAudioTrack(int playerId, String? trackId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.setAudioTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, trackId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setTextTrack(int playerId, String? trackId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.setTextTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, trackId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> disposePlayer(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.disposePlayer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Process-wide disk cache. [maxBytes] 0 disables writes.
  Future<void> configureCache(int maxBytes) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.configureCache$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[maxBytes],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<int> cacheBytes() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.cacheBytes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<void> clearCache() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.clearCache$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> preload(HostMediaSource source) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.preload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[source],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setPictureInPictureAutomatic(int playerId, bool enabled) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.setPictureInPictureAutomatic$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, enabled],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> enterPictureInPicture(
    int playerId,
    int? aspectWidth,
    int? aspectHeight,
    HostPipSourceRect? sourceRect,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.enterPictureInPicture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, aspectWidth, aspectHeight, sourceRect],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> exitPictureInPicture(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.exitPictureInPicture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setBackgroundAudioEnabled(int playerId, bool enabled) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.setBackgroundAudioEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, enabled],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setNowPlaying(
    int playerId,
    String? title,
    String? artist,
    String? album,
    String? artworkUri,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_core.PlayerHostApi.setNowPlaying$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, title, artist, album, artworkUri],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

Stream<HostPlayerEvent> events({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel eventsChannel = EventChannel(
    'dev.flutter.pigeon.player_core.PlayerEventChannel.events$instanceName',
    pigeonMethodCodec,
  );
  return eventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as HostPlayerEvent;
  });
}
