// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum HostCastSessionState { unavailable, idle, connecting, connected }

enum HostCastPlaybackState {
  idle,
  loading,
  ready,
  playing,
  paused,
  buffering,
  completed,
  error,
  disposed,
}

enum HostCastErrorCode {
  sourceUnreachable,
  sourceUnsupported,
  decodeFailed,
  timedOut,
  licenseDenied,
  unknown,
}

enum HostCastEventKind {
  sessionState,
  devices,
  error,
  playbackState,
  position,
  tracks,
}

enum HostCastTrackKind { audio, text, video }

class HostCastTrack {
  HostCastTrack({
    required this.id,
    required this.kind,
    this.language,
    this.label,
    this.width,
    this.height,
    this.bitrate,
  });

  String id;

  HostCastTrackKind kind;

  String? language;

  String? label;

  int? width;

  int? height;

  int? bitrate;

  List<Object?> _toList() {
    return <Object?>[id, kind, language, label, width, height, bitrate];
  }

  Object encode() {
    return _toList();
  }

  static HostCastTrack decode(Object result) {
    result as List<Object?>;
    return HostCastTrack(
      id: result[0]! as String,
      kind: result[1]! as HostCastTrackKind,
      language: result[2] as String?,
      label: result[3] as String?,
      width: result[4] as int?,
      height: result[5] as int?,
      bitrate: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostCastTrack || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(language, other.language) &&
        _deepEquals(label, other.label) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(bitrate, other.bitrate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostCastDevice {
  HostCastDevice({required this.id, required this.name, this.model});

  String id;

  String name;

  String? model;

  List<Object?> _toList() {
    return <Object?>[id, name, model];
  }

  Object encode() {
    return _toList();
  }

  static HostCastDevice decode(Object result) {
    result as List<Object?>;
    return HostCastDevice(
      id: result[0]! as String,
      name: result[1]! as String,
      model: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostCastDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(name, other.name) &&
        _deepEquals(model, other.model);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostCastEvent {
  HostCastEvent({
    required this.kind,
    this.sessionState,
    this.devices,
    this.errorCode,
    this.errorMessage,
    this.nativeDetails,
    this.isRecoverable,
    this.playbackState,
    this.positionMs,
    this.durationMs,
    this.tracks,
    this.activeTrackIds,
  });

  HostCastEventKind kind;

  HostCastSessionState? sessionState;

  List<HostCastDevice>? devices;

  HostCastErrorCode? errorCode;

  String? errorMessage;

  String? nativeDetails;

  bool? isRecoverable;

  HostCastPlaybackState? playbackState;

  int? positionMs;

  int? durationMs;

  List<HostCastTrack>? tracks;

  List<String>? activeTrackIds;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      sessionState,
      devices,
      errorCode,
      errorMessage,
      nativeDetails,
      isRecoverable,
      playbackState,
      positionMs,
      durationMs,
      tracks,
      activeTrackIds,
    ];
  }

  Object encode() {
    return _toList();
  }

  static HostCastEvent decode(Object result) {
    result as List<Object?>;
    return HostCastEvent(
      kind: result[0]! as HostCastEventKind,
      sessionState: result[1] as HostCastSessionState?,
      devices: (result[2] as List<Object?>?)?.cast<HostCastDevice>(),
      errorCode: result[3] as HostCastErrorCode?,
      errorMessage: result[4] as String?,
      nativeDetails: result[5] as String?,
      isRecoverable: result[6] as bool?,
      playbackState: result[7] as HostCastPlaybackState?,
      positionMs: result[8] as int?,
      durationMs: result[9] as int?,
      tracks: (result[10] as List<Object?>?)?.cast<HostCastTrack>(),
      activeTrackIds: (result[11] as List<Object?>?)?.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostCastEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(sessionState, other.sessionState) &&
        _deepEquals(devices, other.devices) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(errorMessage, other.errorMessage) &&
        _deepEquals(nativeDetails, other.nativeDetails) &&
        _deepEquals(isRecoverable, other.isRecoverable) &&
        _deepEquals(playbackState, other.playbackState) &&
        _deepEquals(positionMs, other.positionMs) &&
        _deepEquals(durationMs, other.durationMs) &&
        _deepEquals(tracks, other.tracks) &&
        _deepEquals(activeTrackIds, other.activeTrackIds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is HostCastSessionState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is HostCastPlaybackState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is HostCastErrorCode) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is HostCastEventKind) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is HostCastTrackKind) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is HostCastTrack) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is HostCastDevice) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is HostCastEvent) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostCastSessionState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostCastPlaybackState.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostCastErrorCode.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostCastEventKind.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostCastTrackKind.values[value];
      case 134:
        return HostCastTrack.decode(readValue(buffer)!);
      case 135:
        return HostCastDevice.decode(readValue(buffer)!);
      case 136:
        return HostCastEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

class CastHostApi {
  /// Constructor for [CastHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CastHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<HostCastSessionState> initialize(String receiverAppId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[receiverAppId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HostCastSessionState;
  }

  Future<void> startDiscovery() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.startDiscovery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stopDiscovery() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.stopDiscovery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> connect(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> disconnect() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> load(
    String uri,
    int? positionMs,
    String? title,
    String? contentType,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.load$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri, positionMs, title, contentType],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> play() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> pause() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> seek(int positionMs) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.seek$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[positionMs],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setVolume(double volume) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.setVolume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[volume],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setMute(bool mute) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.setMute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[mute],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setPlaybackSpeed(double speed) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.setPlaybackSpeed$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[speed],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setActiveTracks(List<String> trackIds) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_cast.CastHostApi.setActiveTracks$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[trackIds],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

Stream<HostCastEvent> events({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel eventsChannel = EventChannel(
    'dev.flutter.pigeon.player_cast.CastEventChannel.events$instanceName',
    pigeonMethodCodec,
  );
  return eventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as HostCastEvent;
  });
}
