// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum HostAdState { idle, loading, playing, paused, skipped, completed, error }

enum HostAdEventKind { state, ad }

class HostAdInfo {
  HostAdInfo({
    this.title,
    this.durationMs,
    required this.positionMs,
    this.skipOffsetMs,
    required this.canSkip,
    required this.isSkippable,
    required this.indexInPod,
    required this.podSize,
  });

  String? title;

  int? durationMs;

  int positionMs;

  int? skipOffsetMs;

  bool canSkip;

  bool isSkippable;

  int indexInPod;

  int podSize;

  List<Object?> _toList() {
    return <Object?>[
      title,
      durationMs,
      positionMs,
      skipOffsetMs,
      canSkip,
      isSkippable,
      indexInPod,
      podSize,
    ];
  }

  Object encode() {
    return _toList();
  }

  static HostAdInfo decode(Object result) {
    result as List<Object?>;
    return HostAdInfo(
      title: result[0] as String?,
      durationMs: result[1] as int?,
      positionMs: result[2]! as int,
      skipOffsetMs: result[3] as int?,
      canSkip: result[4]! as bool,
      isSkippable: result[5]! as bool,
      indexInPod: result[6]! as int,
      podSize: result[7]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostAdInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) &&
        _deepEquals(durationMs, other.durationMs) &&
        _deepEquals(positionMs, other.positionMs) &&
        _deepEquals(skipOffsetMs, other.skipOffsetMs) &&
        _deepEquals(canSkip, other.canSkip) &&
        _deepEquals(isSkippable, other.isSkippable) &&
        _deepEquals(indexInPod, other.indexInPod) &&
        _deepEquals(podSize, other.podSize);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostAdEvent {
  HostAdEvent({
    required this.kind,
    this.state,
    this.ad,
    this.errorCode,
    this.errorMessage,
  });

  HostAdEventKind kind;

  HostAdState? state;

  HostAdInfo? ad;

  String? errorCode;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[kind, state, ad, errorCode, errorMessage];
  }

  Object encode() {
    return _toList();
  }

  static HostAdEvent decode(Object result) {
    result as List<Object?>;
    return HostAdEvent(
      kind: result[0]! as HostAdEventKind,
      state: result[1] as HostAdState?,
      ad: result[2] as HostAdInfo?,
      errorCode: result[3] as String?,
      errorMessage: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostAdEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(state, other.state) &&
        _deepEquals(ad, other.ad) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is HostAdState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is HostAdEventKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is HostAdInfo) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is HostAdEvent) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostAdState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostAdEventKind.values[value];
      case 131:
        return HostAdInfo.decode(readValue(buffer)!);
      case 132:
        return HostAdEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

class AdsHostApi {
  /// Constructor for [AdsHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AdsHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_ads.AdsHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> bind(int playerId, String tag) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_ads.AdsHostApi.bind$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, tag],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> clear(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_ads.AdsHostApi.clear$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> skip(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_ads.AdsHostApi.skip$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

Stream<HostAdEvent> events({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel eventsChannel = EventChannel(
    'dev.flutter.pigeon.player_ads.AdsEventChannel.events$instanceName',
    pigeonMethodCodec,
  );
  return eventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as HostAdEvent;
  });
}
