// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum HostDownloadState {
  queued,
  downloading,
  paused,
  completed,
  failed,
  removing,
}

enum HostDownloadEventKind { items, bytesUsed }

enum HostDrmScheme { widevine, fairPlay, clearKey }

class HostDrmConfiguration {
  HostDrmConfiguration({
    required this.scheme,
    this.licenseUrl,
    this.licenseHeaders,
    this.clearKeys,
    this.certificate,
    this.contentId,
  });

  HostDrmScheme scheme;

  String? licenseUrl;

  Map<String, String>? licenseHeaders;

  Map<String, String>? clearKeys;

  Uint8List? certificate;

  String? contentId;

  List<Object?> _toList() {
    return <Object?>[
      scheme,
      licenseUrl,
      licenseHeaders,
      clearKeys,
      certificate,
      contentId,
    ];
  }

  Object encode() {
    return _toList();
  }

  static HostDrmConfiguration decode(Object result) {
    result as List<Object?>;
    return HostDrmConfiguration(
      scheme: result[0]! as HostDrmScheme,
      licenseUrl: result[1] as String?,
      licenseHeaders: (result[2] as Map<Object?, Object?>?)
          ?.cast<String, String>(),
      clearKeys: (result[3] as Map<Object?, Object?>?)?.cast<String, String>(),
      certificate: result[4] as Uint8List?,
      contentId: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostDrmConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(scheme, other.scheme) &&
        _deepEquals(licenseUrl, other.licenseUrl) &&
        _deepEquals(licenseHeaders, other.licenseHeaders) &&
        _deepEquals(clearKeys, other.clearKeys) &&
        _deepEquals(certificate, other.certificate) &&
        _deepEquals(contentId, other.contentId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostDownloadRequest {
  HostDownloadRequest({
    required this.id,
    required this.uri,
    this.headers,
    this.title,
    this.drm,
    this.maxHeight,
    this.maxBitrate,
    this.audioLanguage,
    this.textLanguage,
  });

  String id;

  String uri;

  Map<String, String>? headers;

  String? title;

  HostDrmConfiguration? drm;

  int? maxHeight;

  int? maxBitrate;

  String? audioLanguage;

  String? textLanguage;

  List<Object?> _toList() {
    return <Object?>[
      id,
      uri,
      headers,
      title,
      drm,
      maxHeight,
      maxBitrate,
      audioLanguage,
      textLanguage,
    ];
  }

  Object encode() {
    return _toList();
  }

  static HostDownloadRequest decode(Object result) {
    result as List<Object?>;
    return HostDownloadRequest(
      id: result[0]! as String,
      uri: result[1]! as String,
      headers: (result[2] as Map<Object?, Object?>?)?.cast<String, String>(),
      title: result[3] as String?,
      drm: result[4] as HostDrmConfiguration?,
      maxHeight: result[5] as int?,
      maxBitrate: result[6] as int?,
      audioLanguage: result[7] as String?,
      textLanguage: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostDownloadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(uri, other.uri) &&
        _deepEquals(headers, other.headers) &&
        _deepEquals(title, other.title) &&
        _deepEquals(drm, other.drm) &&
        _deepEquals(maxHeight, other.maxHeight) &&
        _deepEquals(maxBitrate, other.maxBitrate) &&
        _deepEquals(audioLanguage, other.audioLanguage) &&
        _deepEquals(textLanguage, other.textLanguage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostDownloadItem {
  HostDownloadItem({
    required this.id,
    required this.uri,
    this.title,
    required this.state,
    required this.progress,
    required this.bytesDownloaded,
    this.bytesTotal,
    this.errorCode,
    this.errorMessage,
    this.playbackUri,
  });

  String id;

  String uri;

  String? title;

  HostDownloadState state;

  double progress;

  int bytesDownloaded;

  int? bytesTotal;

  String? errorCode;

  String? errorMessage;

  String? playbackUri;

  List<Object?> _toList() {
    return <Object?>[
      id,
      uri,
      title,
      state,
      progress,
      bytesDownloaded,
      bytesTotal,
      errorCode,
      errorMessage,
      playbackUri,
    ];
  }

  Object encode() {
    return _toList();
  }

  static HostDownloadItem decode(Object result) {
    result as List<Object?>;
    return HostDownloadItem(
      id: result[0]! as String,
      uri: result[1]! as String,
      title: result[2] as String?,
      state: result[3]! as HostDownloadState,
      progress: result[4]! as double,
      bytesDownloaded: result[5]! as int,
      bytesTotal: result[6] as int?,
      errorCode: result[7] as String?,
      errorMessage: result[8] as String?,
      playbackUri: result[9] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostDownloadItem || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(uri, other.uri) &&
        _deepEquals(title, other.title) &&
        _deepEquals(state, other.state) &&
        _deepEquals(progress, other.progress) &&
        _deepEquals(bytesDownloaded, other.bytesDownloaded) &&
        _deepEquals(bytesTotal, other.bytesTotal) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(errorMessage, other.errorMessage) &&
        _deepEquals(playbackUri, other.playbackUri);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HostDownloadEvent {
  HostDownloadEvent({required this.kind, this.items, this.bytesUsed});

  HostDownloadEventKind kind;

  List<HostDownloadItem>? items;

  int? bytesUsed;

  List<Object?> _toList() {
    return <Object?>[kind, items, bytesUsed];
  }

  Object encode() {
    return _toList();
  }

  static HostDownloadEvent decode(Object result) {
    result as List<Object?>;
    return HostDownloadEvent(
      kind: result[0]! as HostDownloadEventKind,
      items: (result[1] as List<Object?>?)?.cast<HostDownloadItem>(),
      bytesUsed: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostDownloadEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(items, other.items) &&
        _deepEquals(bytesUsed, other.bytesUsed);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is HostDownloadState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is HostDownloadEventKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is HostDrmScheme) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is HostDrmConfiguration) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is HostDownloadRequest) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is HostDownloadItem) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is HostDownloadEvent) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostDownloadState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostDownloadEventKind.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : HostDrmScheme.values[value];
      case 132:
        return HostDrmConfiguration.decode(readValue(buffer)!);
      case 133:
        return HostDownloadRequest.decode(readValue(buffer)!);
      case 134:
        return HostDownloadItem.decode(readValue(buffer)!);
      case 135:
        return HostDownloadEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

class DownloadHostApi {
  /// Constructor for [DownloadHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DownloadHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<HostDownloadItem>> initialize() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_downloads.DownloadHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<HostDownloadItem>();
  }

  Future<String> enqueue(HostDownloadRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_downloads.DownloadHostApi.enqueue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<void> pause(String id) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_downloads.DownloadHostApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> resume(String id) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_downloads.DownloadHostApi.resume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancel(String id) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_downloads.DownloadHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> remove(String id) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_downloads.DownloadHostApi.remove$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> removeAll() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_downloads.DownloadHostApi.removeAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<int> bytesUsed() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.player_downloads.DownloadHostApi.bytesUsed$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }
}

Stream<HostDownloadEvent> events({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel eventsChannel = EventChannel(
    'dev.flutter.pigeon.player_downloads.DownloadEventChannel.events$instanceName',
    pigeonMethodCodec,
  );
  return eventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as HostDownloadEvent;
  });
}
